### ISSUE TITLE
Config With Docker-compose file 

### ISSUE THREAD

**Issue by mozzhead164** [geoffh1977/docker-keepalived#1]
Sorry to leave this as an issue

I am trying to implement this with Docker Swarm in a docker-compose file (+docker stack deploy...)
I have pulled your arm32v7 image and built it on one of my Raspberry pi 4's and pushed it to a local registry...

Here is an extract from the compose file
```
keepalived:
    image: localhost:5000/keepalived:arm32v7
    networks:
      - traefik-net
    environment:
      ROUTER_ID: 111
      INTERFACE: eth0
      PASSWORD: *Redacted*
      VIRTUAL_IP: '192.168.0.119'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
         order: start-first
         parallelism: 1
         delay: 25s
         failure_action: rollback
         monitor: 10s
      restart_policy:
         condition: any
         delay: 25s
         max_attempts: 5
         window: 30s
      placement:
         constraints:
            - node.role==manager
```

But when i bring the stack up i get the following error message...
```
stack_keepalived.1.gu4kbgh0b15y@p8    | Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/sbin/keepalived)
```

Do you know a possible cause to this?
Will keep trying to crack the problem later on today.

Many thanks for your work in this!
